electron/libchromiumcontent

chromiumcontent/chromiumcontent.gypi, patches/third_party/WebKit/cpp11.patch
This allows us to use C++11 libraries.
=> Link with libc++ on Mac

chromiumcontent/chromiumcontent.gyp, script/create-dist
It is required for fixing https://github.com/atom/electron/issues/940.
=> Include ui_zoom in libchromiumcontent

README.md, chromiumcontent/chromiumcontent.gypi, script/update
This is the initial work of ARM build of libchromiumcontent, it still fails for now and I don't have enough time to make it happen. Anyone who is interested in ARM build can start from here.
=> WIP: ARM build

script/create-dist
Refs: https://github.com/atom/electron/issues/1361.
=> Ship ui_unscaled_resources.rc on Windows

patches/accelerator.patch, patches/allow_new_privs.patch, patches/blink_editing_behavior.patch, patches/blink_file_path.patch, patches/blink_scoped_run_v8_script.patch, patches/blink_web_array_buffer.patch, patches/dom_storage_map.patch, patches/frame_host_manager.patch, patches/net_url_request_job.patch, patches/no_stack_dumping.patch, patches/render_widget_host_view_mac.patch, patches/resource_request_details.patch, patches/use_transparent_window.patch, patches/web_contents_impl.patch, script/create-dist
Now apparently no one else is using libchromiumcontent or brightray except for Electron, maintaining an extra atom branch is like hell and let's just merge it to master branch.
=> Merge atom branch to master branch

patches/gpu_memory_buffer_video_frame_pool.patch
=> Backport https://codereview.chromium.org/1500713003

chromiumcontent/chromiumcontent.gypi, script/create-dist, tools/generate_filenames_gypi.py
=> Build ffmpeg as shared library

chromiumcontent/chromiumcontent.gypi, script/build, script/create-dist, script/lib/util.py, script/update
=> Add build of ffmpeg without proprietary codecs

patches/osx_10_11_BUILD.patch
these diffs were pulled from various chromium bugs and fix the build on 10.11. I don't have a machine available with 10.10 to make sure it is backwards compatible
=> fix OS X 10.11 build

patches/disable_hidden.patch
Refs https://github.com/electron/electron/issues/4925.
=> Add patch to prevent render widget from getting hide

patches-mas/no_private_api.patch
Close https://github.com/electron/electron/issues/5618.
=> Comment out AXTextMarker* APIs for MAS build

script/create-dist
They are not supposed to be linked with final product.
=> Do not ship libraries used by protoc

script/create-dist
Refs https://github.com/electron/electron/issues/6587.
=> Ship a few more resources files

patches/blink_world_context.patch
Needed by https://github.com/electron/electron/pull/8348
=> Add patch to expose context for world id

patches/webm_muxer_fix.patch
@see #253 
@see  https://codereview.chromium.org/2617143003
Thanks.
=> Add patch for WebmMuxer

patches-mas/no_private_api.patch
Refs https://github.com/electron/electron/issues/8555.
=> Do not call CGSSetWindowBackgroundBlurRadius under MAS build

patches/worker_context_will_destroy.patch
Refs https://github.com/electron/electron/pull/8852.
=> Add WillDestroyWorkerContextOnWorkerThread interface

README.md, script/create-dist, script/update
=> arm64 build

.gitmodules, script/bootstrap, script/upload
This was done in https://github.com/electron/libchromiumcontent/pull/280 but needs to be done on the `electron-1-6-x` branch as well since the new CI machines don't have boto installed globally.
This pull request just cherry-picks the commits from that pull request.
=> Use vendored boto

patches/build_gn.patch
This addresses [electron#9443](https://github.com/electron/electron/issues/9443)
=> Use dynamic CRT in the Windows static library build

script/cibuild, script/lib/config.py, script/update
Fixes https://github.com/electron/electron/issues/9854
=> Include Chromium version in output directory path

patches/app_indicator_icon_menu.patch
this fix for issue with disabled submenu if in same position in main menu item disabled
https://github.com/electron/electron/issues/9495
=> linux appIndicator submenu fix

script/cibuild, script/update
See https://github.com/electron/electron/pull/9946#issuecomment-314643181, this folder got left over on one of the CI workspaces and was taking up ~400GB.
=> Run gclient sync with --force on CI

patches/third_party/angle/dcheck.patch, patches/third_party/skia/dcheck.patch, script/create-dist
Follow-up to enabling debug mode.
=> Disabled ASSERT which causes some Electron tests to fail

README.md
Updated the README based on notes and discoveries from yesterday.
cc @vanessayuenn @jkleinsc
=> add notes about CI, releases, usage

patches/frame_host_manager.patch, patches/new_site_instance.patch
This is attempt 2 because commit's went weird
=> Add OnCreateSiteInstanceForNavigation

README.md
A followup to https://github.com/electron/libchromiumcontent/pull/336
=> document how to add a patch

patches/gpu_driver_bug_list.patch
This fixes WebGL issues on some Windows hardware.
=> Cherry-pick upstream patch https://chromium-review.googlesource.com/617387

.circleci/config.yml, patches/render_widget_compositor.patch, script/cibuild
Backports https://chromium-review.googlesource.com/c/575445/
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=695427
Fixes https://github.com/electron/electron/issues/9413
I wasn't able to reproduce the issue, so can't verify if this actually fixes the issue. Backporting it so that anyone interested can verify with the libcc build.
/cc @bpasero
=> Backport fix for flickering web contents on large monitors

.circleci/config.yml, patches/browser_plugin_ime.patch, script/cibuild
This brings back https://github.com/electron/libchromiumcontent/pull/300 that was reverted in https://github.com/electron/libchromiumcontent/pull/330 . Verified locally that it fixes the backspace issue.
/cc @jkleinsc
=> Backport macOS IME backspace fix for 1.6.x

chromiumcontent/args/shared_library.gn, chromiumcontent/args/static_library.gn
Required by a crash fix in Node: https://github.com/nodejs/node/pull/13242.
Refs https://github.com/electron/electron/issues/10571.
=> Turn on v8_promise_internal_field_count=1

patches/042-high-sierra-nvidia-gpu.patch
=> Add patch for nvidia GPU's on High Sierra

patches/high-sierra-nvidia-gpu.patch
https://crbug.com/773705
PR to the `master`: #382
=> Add a patch to fix rendering issues with Nvidia GPU on High Sierra

Jenkinsfile, patches/third_party/skia/freetype-2.patch
=> 1.6.x Freetype 2.8.1 Patch

Jenkinsfile, patches/third_party/skia/freetype-2.patch
=> 1.7.x Freetype 2.8.1 Patch

patches-mips64el/v8/002-Fix-v8-loongson-page-size.patch
See https://github.com/electron/electron/pull/11208#issuecomment-346545546.
=> Add patch to fix the pagesize error in v8 on MIPS64EL

patches/v8/020-cherry_pick_2c75616.patch, patches/v8/021-cherry_pick_676c413.patch, patches/v8/022-cherry_pick_e0d64dc.patch, patches/v8/023-backport_b1cd96e.patch, patches/v8/024-cherry_pick_32141e9.patch, patches/v8/025-cherry_pick_cc55747.patch
=> Add v8 deps for node 8.9.3 upgrade

patches/001-accelerator.patch
Refs https://github.com/electron/libchromiumcontent/pull/430.
=> Revert #349 for electron-1-8-x branch

patches/076_patch_catalog_vuln.patch
Add patch based on changes from 
https://chromium-review.googlesource.com/c/chromium/src/+/804397 
to fix 
https://bugs.chromium.org/p/project-zero/issues/detail?id=1450
/cc @alexeykuzmin @deepak1556
=> add patch to fix catalog vuln

chromiumcontent/BUILD.gn, chromiumcontent/args/static_library.gn, chromiumcontent/build_libs.py, chromiumcontent/config/BUILD.gn, patches/010-build_gn.patch, patches/015-deprecated_register.patch, patches/v8/002-build_gn.patch, script/update
Corresponding Electron PR: https://github.com/electron/electron/pull/11955
=> Official build for 1.8

patches/045-fix-touchpad-lagging-issue.patch
#453
port the touchpad lagging fix to 1.8
=> Add patch to fix touchpad lagging issue to 1.8

patches/v8/037-backport_76c3ac5.patch, patches/v8/038-cherry_pick_dbfe4a49d8.patch, patches/v8/039-cherry_pick_c3458a8.patch, patches/v8/040-cherry_pick_ac0fe8ec.patch
=> V8 patches for upgrading to node v9.7.0 

script/apply-patches, script/lib/patches.py, script/patch.py
The intention is to move all patches related meta info (owner, description, etc.) in a dedicated config.
It will also help us to avoid patches' name and position collisions.
This PR is just a preparation for the bigger change and only includes the following:
- create Patch, PatchesList, and PatchesConfig classes
- use Patch and PatchesList in patch.py script
- slightly improve apply-patches script
/cc @zcbenz, @alespergl
=> Light refactoring of patches related code

patches/077-fix-touchpad-lagging-issue.patch
(cherry picked from commit c74ba9786dbb43894d2bb6ae614ab3fe10942068)
/cc @zcbenz
=> Fix touchpad lagging issue. port from crrev.com/c/867070

patches/039-backport_e8fdb3d.patch
https://bugs.chromium.org/p/chromium/issues/detail?id=765524
Should fix https://github.com/electron/electron/issues/12175
Thanks @bpasero for tracking it down.
=> Backport fix for Local Storage migration

patches-mas/002-no_private_api.patch
Refs https://github.com/electron/electron/issues/12184.
=> Disable private sandbox_check API in mas build

patches-mas/002-no_private_api.patch
=> Disable private sandbox_check API in mas build (master)

patches/common/chromium/dcheck.patch
what it says on the tin, in `dcheck.patch`
=> Remove whitespaces from patchfile

script/bootstrap
We use Python implementation anyway.
/cc @codebytere @nitsakh
=> Do not install PyYAML on bootstrap

patches/common/chromium/.patches.yaml, patches/common/chromium/can_create_window.patch
Patch applies cleanly once more ✨ 
For https://github.com/electron/libchromiumcontent/pull/499.
=> Fix can_create_window.patch

.circleci/config.yml, .gitignore, chromiumcontent/args/native_mksnapshot.gn, script/build, script/create-dist, script/update, script/upload
This PR adds native binaries of mksnapshot for armv7 and arm64 for 1-8-x.
=> arm7v/arm64 mksnapshot binaries for 1-8-x

.circleci/config.yml, .gitignore, chromiumcontent/args/native_mksnapshot.gn, script/build, script/create-dist, script/update, script/upload
This PR adds native binaries of mksnapshot for armv7 and arm64 for master (same as #496).
=> Add component to build mksnapshot binaries for armv7/arm64 (master)

script/apply-patches, script/build, script/create-dist, script/download, script/lib/config.py, script/lib/git.py, script/lib/gn.py, script/lib/ninja.py, script/lib/patches.py, script/run-gn, script/update, script/upload
No breaking changes
(with exception of renamed `--target-arch` → `--target_arch` arg of the `apply-patches` script).
* Move some script constants to a shared "lib/config.py"
* Add and use `git.get_head_commit()`
* Extract Ninja related stuff to "lib/ninja.py"
* Add 'run-gn' script and call it from the 'update' script
* Name an arg "target_arch" instead of "target-arch" for consistency
=> Refactor some scripts

script/update
=> Add flag for enabling sccache

script/reportbuild/.gitignore, script/reportbuild/package-lock.json, script/reportbuild/package.json, script/reportbuild/upload-build-results.js, vsts.yml
This is a configuration to run CI with Visual Studio Team Services (VSTS) CI.
Additionally because VSTS doesn't currently support public build results, this PR includes a script under `script/reportbuild` which posts the result as a comment in the PR with a link to the log which has been uploaded to S3.  See https://github.com/electron/libchromiumcontent/pull/515#issuecomment-380994369 for an example of what it looks like.
=> Configuration for Visual Studio Team Services CI

script/reportbuild/.gitignore, script/reportbuild/package-lock.json, script/reportbuild/package.json, script/reportbuild/upload-build-results.js, vsts.yml
This PR backports #515 to 2-0-x
=> Backport VSTS configuration to 2-0-x

script/run_tests
This will enable us to run only desired test targets.
Allows to include specified targets, or exclude.
=> Update run_tests script to run only specified test targets

script/lib/sccache.py, script/sccache
=> Add wrapper script for the bundled sccache

script/README.md, script/get-patch
- add options to save patch contents to a file
- add usage examples
=> Improve the "get-patch" script

patches/common/webrtc/.patches.yaml, patches/common/webrtc/backport_a157e0809.patch
Reverts electron/libchromiumcontent#560
=> Revert "Revert "backport: VP9 temporal index bounds check""

patches/mas/chromium/no_private_api.patch
Refs https://github.com/electron/electron/issues/13410.
=> Remove some new private APIs in MAS build

patches/common/chromium/dcheck.patch
Reverts electron/libchromiumcontent#573
=> Revert "Revert "Disable a DCHECK in process_metrics_win.cc""

script/lib/filesystem.py
The easiest way to show how much better this is than the old dots is a GIF
https://i.imgur.com/6214pKI.gif
cc @deepak1556 I did it 😄
=> build: improve the download script to show percentage / ratio progress of libcc download

script/download, script/lib/filesystem.py, script/lib/gn.py, script/run-gn, script/update
=> build: improve percentage output in download script

script/sccache
Handle only custom arguments, pass all others to the `sccache` binary.
/cc @nornagon
=> chore: refactor script/sccache

patches/common/chromium/.patches.yaml, patches/common/chromium/mas-audiodeviceduck.patch, patches/common/chromium/mas-cfisobjc.patch, patches/common/chromium/mas-cgdisplayusesforcetogray.patch, patches/common/chromium/mas-lssetapplicationlaunchservicesserverconnectionstatus.patch
=> fix: [mas] remove usage of private APIs

patches/common/chromium/.patches.yaml, patches/common/chromium/mas-audiodeviceduck.patch, patches/common/chromium/mas-cfisobjc.patch, patches/common/chromium/mas-cgdisplayusesforcetogray.patch, patches/common/chromium/mas-lssetapplicationlaunchservicesserverconnectionstatus.patch
See electron/electron#13938
Backports #633 to 3-0-x
=> fix: backport #633 to 3-0-x

appveyor-override.yml, patches-mas/004-no-cgdisplayusesforcetogray-cfisobjc.patch, vsts.yml
See electron/electron#13938
Backports #633, minus AudioDeviceDuck and LaunchServices APIs (because they aren't in use in this version of chromium)
=> fix: backport MAS api removal to 1-8-x

appveyor-override.yml, patches-mas/004-no-cgdisplayusesforcetogray-cfisobjc.patch, vsts.yml
See electron/electron#13938
Backports (parts of) #633
=> fix: backport MAS api removal to 1-7-x

script/create-dist
For https://github.com/electron/electron/pull/14107
=> build: [gyp] ship //net:extras for component build

patches/common/chromium/.patches.yaml, patches/common/chromium/windows_cc_wrapper.patch
=> build: Enable sccache for Windows

patches/common/chromium/can_create_window.patch
=> build: fix Chromium tests compilation with Electron patches

patches/common/chromium/.patches.yaml, patches/common/chromium/content_browser_manifest.patch, script/create-dist
Backports https://github.com/electron/libchromiumcontent/pull/659 and https://github.com/electron/libchromiumcontent/pull/651
=> chore: backport some commits to 3-0-x

patches/common/chromium/.patches.yaml, patches/common/chromium/vmware_gpu_acceleration.patch
Backports https://chromium-review.googlesource.com/c/chromium/src/+/952778
Fixes https://github.com/electron/electron/issues/14270
=> fix: Re-enable GPU acceleration for recent VMWare drivers

script/lib/git.py, script/lib/patches.py, script/patch.py
- do not merge descriptions of our patches into one commit message
- remove unnecessary printing to stdout
=> build: clean up git related scripts

chromiumcontent/BUILD.gn, chromiumcontent/args/shared_library.gn, chromiumcontent/args/static_library.gn, patches/common/chromium/.patches.yaml, patches/common/chromium/chrome_key_systems.patch, script/create-dist
Align with https://github.com/electron/electron/pull/14423 for the gyp build.
=> build: [gyp] cdm key system support behind flag
