README.md
script/bootstrap
script/build
script/cibuild
script/create-dist
script/update
script/upload

This is required for supporting 64bit on Windows, it also makes it possible to do cross building.

Enabling setting target_arch when building

---

README.md

Currently, the minimal required version of VS2013 for building Chromium is Update 4. See https://www.chromium.org/developers/how-tos/build-instructions-windows
As far as I know, VS2013 Update 2 cannot build Chrome41.

:memo: Update required VS2013 version on Windows.

---

script/build
script/create-dist

The building script will build `static_library` and `shared_library` at one time, which requires a lot of time. It would be better to add a switch argument allowing developers to choose the specific building type. @zcbenz PLTAL

Add `--component` argument to specify building type.

---

chromiumcontent/chromiumcontent.gypi

Linking with libcmt seems to cause various weird problems on Windows with Node.js.

Use msvcrt instead of libcmt

---

chromiumcontent/chromiumcontent.gypi

This leaves use least trouble when linking with third party source code like Node.

Link with shared library version of msvcrt

---

patches/export_pdf.patch
script/create-dist

This patch makes the pdf library build from static_library to shared_library. As a side effect, we only ship the pdf.dll, and no need to ship all the pdf related libraries.

Ship pdf component as a shared library

---

script/create-dist

[IDR_DIR_HEADER_HTML](https://code.google.com/p/chromium/codesearch#chromium/src/out/Debug/gen/net/grit/net_resources.h&q=dir_header.html&sq=package:chromium&type=cs&l=5) is required for directory listing.

ftp: including generated network resource

---

patches/export_pdf.patch

The link error in [#115](https://github.com/atom/libchromiumcontent/pull/115#issuecomment-104879030)  is caused by https://codereview.chromium.org/980053002/. We need to add printing component dependency in `pdf` library.
Having test on component-build/non-component-build, as well as test printing feature in `electron`.

Fix pdf.dll link error in component builds after upgrade to Chrome 43.

---

script/create-dist
script/download
tools/generate_filenames_gypi.py

gyp will convert relative paths to absolute paths for us if we store them in appropriately-named variables. Using gyp's automatic path conversion seems to work better when generating Xcode projects. (For example, gyp was complaining about files from libchromiumcontent being included twice in the project, but that error goes away with this change.)
See https://chromium.googlesource.com/external/gyp/+/master/docs/InputFormatReference.md#Pathname-Relativization for the full explanation of gyp's behavior. The essence is that by naming these variables with `*_files` we get the automatic path conversion behavior.
Also, now that `filenames.gypi` doesn't depend on where libchromiumcontent is extracted, we can generate it at build time and include it in the zip file.
/cc @zcbenz

Use relative paths in filenames.gypi

---

chromiumcontent/chromiumcontent.gyp
chromiumcontent/chromiumcontent.gypi
script/create-dist

After some experiments I don't think we actually need it to fix atom/electron#940 now.

Revert "Include ui_zoom in libchromiumcontent"

---

resources/about_credits.tmpl
resources/about_credits_entry.tmpl
script/create-dist
tools/licenses.py

The `licenses.py` is copied from the master branch of Chromium, we can remove our copy when upgraded to Chrome 45.
Fix #137.

Provide Chromium's licenses in dist

---

chromiumcontent/chromiumcontent.gypi
script/update

This PR changes the way of building 32bit target from building in a chroot environment to cross-compilation, so we can have an uniform way of building for all targets on Linux.
The downside is setting up the Linux environment to build 32bit target would be very nasty.

Build 32bit target in the same way with arm target on Linux

---

chromiumcontent/chromiumcontent.gypi

Chromium has not done switching to use OpenSSL on Linux yet, and force using it causes troubles on some distributions.
Refs: https://github.com/atom/electron/issues/1680.

Don't force using OpenSSL on linux

---

patches/third_party/ffmpeg/ffmpeg.patch

This patch is imported from https://codereview.qt-project.org/gitweb?p=qt/qtwebengine-chromium.git;a=commit;h=337abb1a5c73f76ffb8f989c5031cc7a908f472c.
> We need the include override everywhere the C99 methods are overriden otherwise MSVC ends up believing these to be external and look for their DLL hooks.

Fix Windows build with static ffmpeg

---

script/download
tools/generate_filenames_gypi.py

- Currently libchromiumcontent is downloaded by default.
- Now developer can choose to provide local libchromiumcontent src, shared and static path
Tries to solve similar issue noted in: [https://github.com/atom/electron/issues/3310]

Add option to build local libchromiumcontent

---

README.md

While it is a WebKit fork, they have diverged for three years already.

Renamed WebKit to Blink

---

patches/thread-capabilities.patch

Chromium automatically drops all capabilities of renderer threads in
Linux, which may cause issues in a context like Electron, where the main
and renderer threads are supposed to keep inherited permissions over the
system.
See https://github.com/atom/electron/issues/3666

Prevent capabilities from being dropped in renderer threads in Linux

---

patches/render_widget_host_view_mac.patch

This would remove the white flash when loading page on OS X.
Refs https://github.com/atom/electron/issues/861.
Refs https://github.com/atom/electron/issues/1055.

Never set default background color on OS X

---

patches/blink_local_frame.patch

According to electron/electron#3699, it is unreliable to use |unload| event for process.exit('exit'), so we have to do that in willReleaseScriptContext.
However Chromium then disallowed scripting in willReleaseScriptContext in https://codereview.chromium.org/1657583002, and crash will happen when there is code doing that.
This patch reverts the change to fix the crash in Electron.

Allow running script in willReleaseScriptContext

---

patches/third_party/icu/no_inline_default_constructor.patch

It seems that when building with Visual Studio 2015, the inline default constructor of UnicodeString gets compiled in each compilation unit instead of being inlined, results in linking error of the Release build of Electron:
```
blink_platform.lib(blink_platform.SimpleFontData.obj) : error LNK2005: "public: __cdecl icu_54::UnicodeString::UnicodeString(void)" (??0UnicodeString@icu_54@@QEAA@XZ) already defined in node.dll.lib(node.dll)
blink_platform.lib(blink_platform.StringTruncator.obj) : error LNK2005: "public: __cdecl icu_54::UnicodeString::UnicodeString(void)" (??0UnicodeString@icu_54@@QEAA@XZ) already defined in node.dll.lib(node.dll)
blink_platform.lib(blink_platform.FontCacheSkiaWin.obj) : error LNK2005: "public: __cdecl icu_54::UnicodeString::UnicodeString(void)" …
```

Add patch to not inline the default constructor of UnicodeString

---

chromiumcontent/chromiumcontent.gypi

e.g. DLL for component build, static for normal build.

Use standard RuntimeLibrary configuration

---

patches/guest_view.patch

This PR adds a small patch to fix electron/electron#5665
`RenderWidgetHostViewChildFrame` was missing some functions, I tried to keep the implementation as small as possible for easier maintenance.

Fix for webviews using default (empty) BeginFrameSubscription implementation

---

patches/initialize_direct_write_font_proxy.patch

Port over https://codereview.chromium.org/2387373003 which can be removed if/when that lands.
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=620419
Refs https://github.com/electron/electron/issues/7334

Add patch to always call InitializeDWriteFontProxy

---

README.md

The original link has been redirected, so I updated the docs.

docs: update windows build link

---

chromiumcontent/chromiumcontent.gyp
script/create-dist

This is needed for electron/electron#7586 for which we will need to use `ui::KeycodeConverter::DomKeyToKeyString`.

Ship dom_keycode_converter

---

script/cibuild-libchromiumcontent-linux

Our Linux CI machine is currently filling up the logs with thousands of these:
```
/usr/bin/arm-linux-gnueabihf-ld: BFD (GNU Binutils for Ubuntu) 2.22 assertion fail ../../bfd/elf32-arm.c:12049
```
This pull request filters them out so they don't trigger the output limits on Jenkins. This is just a short-term solution, the long-term solution is to upgrade to binutils 2.24+.
https://sourceware.org/bugzilla/show_bug.cgi?id=14189

Filter out BFD assertion from CI logs

---

patches/dom_key_control.patch

This pull request backports the fix for https://codereview.chromium.org/2474083002 to Chrome 53 so apps using `KeyboardEvent.key` on Linux will get correct results.
This patch can be removed when Chrome 56 is upgraded to.
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=633838
Refs https://github.com/electron/electron/issues/8116

Backport Chrome 56 Linux Control key fix to Chrome 53

---

patches/ct_build_not_timely.patch

Adds an upstream patch to prevent a CT timebomb based on the build time of libchromiumcontent.
https://bugs.chromium.org/p/chromium/issues/detail?id=664177
https://codereview.chromium.org/2495583002

Add CT timebomb patch

---

script/cibuild
script/cibuild-libchromiumcontent-linux-arm
script/cibuild-libchromiumcontent-linux-ia32
script/cibuild-libchromiumcontent-linux-x64

Split up the Linux CI into three jobs for each target architecture, x64, ia32, and arm.
This allows individual statuses for each build and the ability to run each build in parallel (someday).

Split up Linux CI jobs

---

chromiumcontent/args/shared_library.gn
script/create-dist

Compile shared library with more debug information, and produce a .zip containing this data, which will make it simpler to debug prebuilt libchromiumcontent binaries on linux/mac. This change won't affect the libchromiumcontent.zip size, since symbols are stripped and stored separately.

Set symbol level for shared_library and create zip with debug info.

---

chromiumcontent/args/static_library.gn
script/create-dist

Otherwise the Release build of Electron won't have debug symbols generated.
This PR also put PDB files into the distribution.

Use symbol_level 2 for static_library build

---

script/create-dist

Fix the warning:
```
libyuv.lib(jsimd_x86_64.obj) : warning LNK4099: PDB 'simd_c.pdb' was not found with 'libyuv.lib(jsimd_x86_64.obj)' or at 'C:\cygwin\home\zcbenz\codes\electron\out\D\simd_c.pdb'; linking object as if no debug info
```

Ship simd_c.pdb for shared_library build

---

patches/stream_resource_handler.patch

This allows us to intercept the resource responses initiated with `ResourceDispatcherImpl` as streams. Pdf rendering depends on this.
https://github.com/electron/electron/pull/8435

add patch to expose StreamResourceHandler

---

patches/verify_snapshot.patch
script/cibuild-libchromiumcontent-linux-arm
script/cibuild-libchromiumcontent-linux-ia32
script/cibuild-libchromiumcontent-linux-x64
script/cibuild.ps1

Backports https://codereview.chromium.org/2680653002 to Chrome 52 so Atom can use snapshots on Windows against Electron 1.3.
Refs https://github.com/atom/atom/pull/13916
/cc @electron/atom

Remove verification of external snapshot data

---

patches/v8/heap-snapshot-generator.patch

Pulls in https://codereview.chromium.org/2669393002 to prevent crashes when taking heap snapshots, https://bugs.chromium.org/p/chromium/issues/detail?id=661223
This can be dropped once Chrome 58 is upgraded to.
Refs https://github.com/electron/electron/issues/8791

Add HeapSnapshotGenerator crash patch

---

script/cibuild-libchromiumcontent-linux

Delete the `dist/` folder and the generated zip files after uploading on Linux CI. These machines have less space than the mac and windows versions so clean up a bit of space after each build.

Delete archives after uploading on CI

---

script/build
script/create-dist
script/lib/config.py
script/update

This is to make the output directory structure more sensible in light of the new GN build. Each configuration (shared_library, etc.) has an equally named subdirectory under an architecture-based `out` directory, e.g.:
```
out-x64
├ ffmpeg
├ shared_library
└ static_library
```

Streamline build output directories

---

chromiumcontent/build_libs.py

This fixes widevine failures with release builds of Electron.
Fixes https://github.com/electron/electron/issues/8824
Ref https://github.com/electron/electron/issues/6516
Since we ask users to use the adapter and plugin from the official chrome builds, do we need to build the `widevinecdmadapter` target ?

Dont include widevine stub code in non component build

---

patches/verify_snapshot.patch

Adds the patch from #271 against master.
Pulls in https://codereview.chromium.org/2680653002

Add patch to disable snapshot verification on Windows

---

patches/scoped_clipboard_writer.patch

This is required to implement `clipboard.writeBuffer()` in Electron.
This patch has also been upstreamed:
https://codereview.chromium.org/2777723002

Add patch to expose ScopedClipboardWriter::WriteData

---

chromiumcontent/build_libs.py

Previously this was statically linking in `ffmpeg` which meant you couldn't swap in the version without the proprietary codecs.
Closes #268 
```sh
> ./node_modules/electron/dist/electron -v
v1.4.15
> nm -D node_modules/electron/dist/electron | grep av_buffer_create
U av_buffer_create
> readelf -d ./node_modules/electron/dist/electron | grep ffmpeg
0x0000000000000001 (NEEDED)             Shared library: [libffmpeg.so]
```
```sh
> ./node_modules/electron/dist/electron -v
v1.6.4
> nm -D node_modules/electron/dist/electron | grep av_buffer_create
000000000349c7a0 T av_buffer_create
> readelf -d node_modules/electron/dist/electron | grep ffmpeg
```
```sh
> ~/Downloads/electron-ffmpeg/electron -v
v1.6.5
> nm -D ~/Downloads/electron-ffmpeg/electron | grep av_buffer_create
U av_buffer_create
> …
```

Don't include ffmpeg as a build lib

---

patches/can_create_window.patch
patches/frame_host_manager.patch

This PR adds `RenderFrameHost` as an argument of `OverrideSiteInstanceForNavigation()`.
This change is used in https://github.com/electron/electron/pull/8963.

Pass RenderFrameHost to OverrideSiteInstanceForNavigation()

---

patches/enable_non_client_dpi_scaling.patch

This is needed to enable non-client area scaling when the screen DPI changes on Windows 10.
It can be removed after upgrade beyond Chromium 56.

Backport calling EnableNonClientDpiScaling

---

script/update

It is causing electron.exe and node.dll to use different allocators, this is fine in Chromium becuase everything has been compiled into the same exe, while in Electron lots of components have been put into node.dll and we have to make sure electron.exe and node.dll use the same allocator.
This is to fix the crash in https://github.com/electron/electron/pull/9116.

Stop using experimental allocator shim on win32

---

patches/v8/build_gn.patch

It shouldn't be necessary to export symbols from these libraries, as they should be used only internally within V8 and we link all of V8 into `node.dll` and don't have separate DLLs for "v8_libbase" and "v8_libplatform."

Don't export symbols from "v8_libbase" and "v8_libplatform"

---

patches/browser_plugin_ime.patch

Backports https://codereview.chromium.org/2689153002/ which fixes a long standing IME bug, can be removed with chromium 59 upgrade.
Fixes https://github.com/electron/electron/issues/3379

backport fix for accented letter input resulting double letters in webview

---

patches/third_party/skia/locale.patch

Backports https://skia-review.googlesource.com/c/13601/
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=711683
Closes https://github.com/electron/electron/issues/9225

Add skia locale patch

---

patches/number_parsing.patch
patches/v8/number_parsing.patch

Backports https://codereview.chromium.org/2866213002 and  https://codereview.chromium.org/2846673005 which have been fixed in Chrome 59.
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=712610
Closes https://github.com/electron/electron/issues/8876

Add inspector number parsing patch

---

patches/work_area_update.patch

Backports https://codereview.chromium.org/2829693003/
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=712871
Closes https://github.com/electron/electron/issues/6312

Add work area update patch

---

patches/render_widget_mac_ime.patch

Backports https://codereview.chromium.org/2901443002/
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=714771
Fixes https://github.com/electron/electron/issues/9173

Backport macOS IME backspace fix

---

patches/v8/build_gn.patch

This is now needed by https://github.com/electron/electron/pull/9473 since `CreateDefaultPlatform` is used when creating the inspector agent.
/cc @alespergl 
Reverts electron/libchromiumcontent#291
Closes https://github.com/electron/electron/issues/9548

Revert "Don't export symbols from "v8_libbase" and "v8_libplatform""

---

patches/render_widget_mac_ime.patch

Backports #300 to Chrome 56 (Electron 1.6.x).
/cc @CharlieHess @deepak1556

Add RenderWidget patch for macOS IME backspace fix

---

patches/resource_multibuffer_data_provider.patch

Backports https://codereview.chromium.org/2714583002 to Chrome 56.
Refs https://bugs.chromium.org/p/chromium/issues/detail?id=689989
This does not affect Chrome 58 (Electron 1.7.x) so it is only being backported to Chrome 56 (Electron 1.6.x)
/cc @deepak1556 @CharlieHess

Add patch that removes setting If-Match headers

---

script/cibuild-libchromiumcontent-linux

Linux builds are still green when failing without since `grep` is used to filter out thousands of ignored warnings.

Set pipefail to catch cibuild errors

---

patches/webgl_context_attributes.patch
patches/worker_context_will_destroy.patch
patches/zzz_webgl_context_attributes.patch

This patch adds `powerPreference` to `WebGLContextAttributes`, which allows to optionally prefer using the integrated GPU for WebGL contexts:
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1
Closes https://github.com/electron/electron/issues/9528

Add webgl_context_attributes patch

---

patches/app_indicator_icon_menu.patch

this fix for issue with disabled submenu if in same position in main menu item disabled
electron/electron#9495
port from 1-6-0

linux appIndicator submenu fix

---

script/upload

Looks like a couple recent builds were marked as passing even though the upload script failed.
This pull request update the boto call to use `check_call` to surface errors.
http://208.52.191.140:8080/job/libchromiumcontent-osx/420/console

Surface boto process errors

---

script/apply-patches

This fix is compatible to any setup you choose for your LIBCC build. 
If you don't want to use `gclient`, then the `src` folder will not be a git repo and the current approach will fail applying patches (actually skipping them). The reason for this might be that you are not allowed to fetch dependencies from outside of your network and everything needs to be "cooked" in house.

Apply patches fix for cases when src is not a git repo

---

chromiumcontent/args/shared_library.gn
patches/dcheck.patch
patches/v8/dcheck.patch

This PR enables debug mode in the shared_library build configuration, which is consumed by the debug ("D") configuration of Electron. It will allow contributors to catch some bugs before they slip through to released binaries. It will also reveal existing bugs!
There are currently known bugs which are flagged by the DCHECK macro in runtime which prevents Electron to even launch. Some of these bugs are not trivial to fix, so there needs to be some transition to fully checked debug builds. This transition is enabled by temporarily disabling the DCHECK macro.
The goal of this is to have a better, safer Electron. 🌻 🌞

Enable debug mode for "shared_library"

---

.dockerignore
.gitignore
Dockerfile
patches/deprecated_register.patch
patches/third_party/swiftshader/gold_ifc.patch
script/cibuild-libchromiumcontent-linux
script/docker-install-build-deps.sh

Allows us to easily update the distro and config for the prebuilt Linux libraries.
Will merge into #313 once the build goes green here so those builds can successfully complete.
Copies in https://chromium.googlesource.com/chromium/src/+/lkcr/build/install-build-deps.sh and tweaks it so it can be run in Docker.
Refs https://github.com/electron/libchromiumcontent/pull/313#issuecomment-311901269

Use Docker for Linux builds

---

script/apply-patches
script/lib/git.py
script/patch.py

**Motivation**:
`apply-patches` script is perfectly fine when patches could be applied without any errors,
but during upgrades to a new Chromium version it's almost useless.
`patch.py` should make work with failing patches more versatile and easier.

Add `script/patch.py` to use during Chromium upgrades

---

patches/build_gn.patch

Further CI tests fail (on Linux) due to a memory corruption flagged in the debug mode. This disables the debug allocation framework to prevent those failures.

Disabled debug allocation as it causes some Electron tests to fail

---

patches/build_toolchain_win_patch.patch

When the PDB files generated by the static_library build are packaged for distribution they are all copied to a single folder, some of the PDB files have identical names so they end up overwriting each other. The missing PDB files cause linker warnings when building Electron in Release mode, and make it more difficult
to debug release builds.
This patch modifies the PDB naming convention for the static_library build configuration to ensure PDB names are unique. For example, instead of generating obj/ui/base/base_cc.pdb the build will now generate obj/ui/base/obj_ui_base_base_cc.pdb.

Patch the Windows build toolchain to generate unique PDB names

---

chromiumcontent/args/shared_library.gn
patches/build_gn.patch

This turns off the debug mode for the shared_library build configuration for the time being, as was agreed by the maintainers. There's no need to revert the "dcheck" patches, as they have no effect in non-debug mode.

Turned off debug mode in shared_library

---

.gclient
.gitignore
README.md
script/build
script/create-dist
script/update
tools/copy.py

Goal of this PR is to make libchromiumcontent build system more friendly for development with electron by speeding up the modify/compile/debug cycles.
The biggest change is a modification to `create-dist`, which instead of copying all compiled libraries to `dist/main`, it generates a ninja file that does the copy and persists after the script exits.
The reason for this change is to allow incremental copying, which is good when developing libchromiumcontent inside electron tree. For example, right now we need to do something like this when making changes to chromium files and bootstrapping electron with `./bootstrap.py --build_libchromiumcontent`:
$ ninja -C vendor/libchromiumcontent/src/out-x64/shared_library
$ ./vendor/libchromiumcontent/script/create-dist -t x64 -c shared_library …

Improvements for libcc development

---

chromiumcontent/args/shared_library.gn
patches/010-build_gn.patch

This PR re-introduces debug mode for the shared_library configuration.
It was disabled because there were issues with it when Electron tests were executed as part of the Linux CI build - the tests hung inexplicably. It turns out that the thing that causes the hangs is the tcmalloc allocator library, which (when run inside Docker) deadlocks while trying to allocate memory.
The way tcmalloc works is by replacing the `malloc` family of APIs normally provided by the C runtime library. Supposedly on Linux, tcmalloc has better performance compared to the default, which is why Chromium uses it. It's not used on other platforms.
I was unable to explain why the deadlock condition occurs in Docker and not elsewhere. Nevertheless, I decided to just disable tcmalloc for the shared_library build, …

Re-enabled debug mode, and disabled tcmalloc for shared_library build

---

script/create-dist
tools/generate_filenames_gypi.py

Sonames do not always match '*.so' pattern,
sometimes they have a version number as a suffix, e.g. "libfreetype.so.6".

Collect more shared libraries on Linux

---

script/update

Found during our internal builds that the update script is trying to download this on Windows and Mac, which is not needed for the `is_official` libchromiumcontent build.

Don't download llvm gold on windows and mac

---

.gitmodules
chromiumcontent/BUILD.gn
chromiumcontent/args/ffmpeg.gn
chromiumcontent/args/static_library.gn
chromiumcontent/build_libs.py
patches/025-no_stack_dumping.patch
script/bootstrap
script/update
script/upload

**UPD** Electron Release builds on Windows and Linux x64 fail electron/electron#10726 after the `is_official_build=true` was added.
```
Revert "Merge pull request #361 from electron/use-official-build-for-static-library"
This reverts commit 628f0d99441016270750fda6b0781107c8d9cd76, reversing
changes made to c073406bd0256846e1074bb74e9b6265bd80d2fa.
Revert "Merge pull request #367 from electron/cifratila/download_llvm_gold_fix"
This reverts commit d6df80e20748f35373f15c2bfbd70befb4bb6221, reversing
changes made to 628f0d99441016270750fda6b0781107c8d9cd76.
```

Disable Official Build

---

patches/001-accelerator.patch

Fixes the issue when zoom-in accelerator "Ctrl +" was displayed as "Ctrl Shift =".
This should be fixed for both Win and Lin.
Related issue: electron/electron#6731

Don't expand shifted keys in accelerators

---

patches/v8/008-turn_off_escape_analysis.patch

Fixes a security vulnerability in V8's Turbofan engine.
For detailed description see
https://blogs.technet.microsoft.com/mmpc/2017/10/18/browser-security-beyond-sandboxing/
https://crbug.com/765433
https://chromium-review.googlesource.com/670563

[turbofan] Temporarily turn off escape analysis.

---

patches/042-high-sierra-nvidia-gpu.patch

This is a redo of @MarshallOfSound's PR #377 that was merged into master a bit prematurely by myself.  This needs to be tested against a 1.8 Electron build before merging.

Add patch for nvidia GPU's on High Sierra (redo #377)

---

.circleci/config.yml
Jenkinsfile
script/cibuild
script/cibuild.ps1

This PR does a couple of things:
1. Allows builds of forked PRs.  Forked PRs were not properly building because AppVeyor and CircleCI don't pass the S3 credentials to PRs that come from forks, and this is a good thing because **security**.  This change will allow those prs to build, but they won't upload to S3.  Eventually once we introduce tests to libchromiumcontent we can run those test for these type of PRs.
2. Storage of libchromiumcontent.zip and libchromiumcontent-static.zip as artifacts on the CI build.  This is particularly useful for PRs that come from forks because those builds don't get uploaded to S3 (see 1.)
3. Adds a Jenkins pipeline build for libcc.  These builds can be specifically restarted unlike our current Jenkins setup where you can only re-run the last build that …

CI updates for building forked PRs

---

patches/042-webui_in_subframes.patch

This PR is a proposal to fix the issue https://github.com/electron/electron/issues/9192
The patch is fixing the following issues:
1) The  sub frame inherit the bindings from the main frame which does not have the web ui bindings.
Th fix is to reset the bindings fro the sub frame during the navigation
2) The user needs to set a name for the sub frame otherwise the web ui will be displayed in the main frame.  This limitation is removed by generating a name from the id for the sub frame when it hosts a web ui. A better approach would be to use the frame node id but this need a change in the chromium design for web ui which is based on the frame name.
3)  Messages are passed only to the web ui in the main frame. The fix is to iterate recursively the child frames and pass the message.

Add patch for pdf support in sub frames

---

.circleci/config.yml

The logic checking for the S3 environment variables was backwards, thus causing CircleCI to not upload to S3.

Fix upload logic

---

patches/webrtc_crash_fix.patch

See https://codereview.chromium.org/2772283002 for the original fix, this fix is in Chromium 59 already so doesn't need to go to the 1-8-x/master series

Backport webrtc crash fix to electron 1.7.x

---

chromiumcontent/build_libs.py

The `third_party/libdrm` is build and used by some code of content module, but the linker could build electron without it since electron is not using related code. However the linker of mips64el is not so advanced to optimize the dependency out and we have to ship it as part of libcc.

Collect objects from third_party/libdrm

---

.circleci/config.yml
Jenkinsfile
appveyor.yml
script/build
script/cibuild
script/create-dist

As requested by @alexeykuzmin, this PR  breaks up builds of shared_library and static_library configurations into separate builds which will allow us to speed up our builds.

Split builds into static and shared builds

---

Jenkinsfile

`libchromiumcontent-static.zip` for MAS was being incorrectly uploaded as `libchromiumcontent-static.zip'`

Remove extraneous single quote from filename

---

patches/third_party/webrtc/001-fix_laggy_mouse_during_desktop_capture.patch

The mouse is being capture twice, one time with a custom way
and one time with a built-in Mac API. The later was not known
so the mouse was wrongly captured twice.
Also the later way causes the cursor to move slowly on the
machine that is being captured.
The solution is just to disable this build-in way to just
keep the former way.
https://webrtc-review.googlesource.com/c/src/+/30902

[webrtc][mac] cherry-pick fix for laggy mouse during desktop capture

---

patches/002-dcheck.patch
patches/052-latency_histogram_macros.patch

Backports https://chromium-review.googlesource.com/780182
Fixes https://github.com/electron/electron/issues/11485

Backport patch that removes DCHECK in latency recording macros

---

patches/073-gin_enable_disable_v8_platform.patch

This is part of the fix for the V8 startup dead lock problem on Chrome61. The same patch has already been applied on the Chrome62 branch.
/cc @alexeykuzmin The patch is identical and you may encounter conflicts when rebasing.

Add patch to allow disabling gin's V8 platform

---

Jenkinsfile
patches/third_party/skia/003-freetype-2.patch

Add freetype 2.8.1 patch

---

patches/third_party/webrtc/001-fix_laggy_mouse_during_desktop_capture.patch

Backports https://webrtc-review.googlesource.com/c/src/+/30902
Refs https://github.com/electron/libchromiumcontent/pull/417

[webrtc] Backport patch that fixes laggy mouse during desktop capture

---

patches/v8/032-cherry_pick_c690f54d95802.patch
patches/v8/033-cherry_pick_98c40a4bae915.patch
patches/v8/034-patch_v8.patch
patches/v8/035-backport_14ac02c.patch
patches/v8/036-cherry_pick_1420e44db0.patch

I'm fairly certain we don't need to apply either of these since the first is reverted by the second:
- 47cd49a8cb deps: backport 3c8195d from V8 upstream
- 465a32a087 Revert "deps: cherry-pick 3c8195d from V8 upstream"

Upgrade Node to 9.3.0 for C62

---

.circleci/config.yml

The fix for Intel bugs are slowing down our CI machine, making the mips64el job timeout. Will look into this in future.

Disable the mips64el job on electron-1-8-x

---

patches/003-accelerator.patch

#349 made some accelerators like `Ctrl+Shift+A` and `Ctrl+Shift+F11` show without the `Shift` key. I tried tweak the patch but can not find a easy fix, so I'm reverting it since it is preventing 1.8.x stable.
Refs https://github.com/electron/electron/issues/11429.

Revert #349 for master branch

---

patches/third_party/webrtc/001-webrtc-desktop_capturer_mac.patch
patches/third_party/webrtc/002-webrtc-desktop_capturer_mac.patch
patches/third_party/webrtc/003-webrtc-rwlock_null.patch

Fixes crash described in https://github.com/electron/electron/issues/9600, https://github.com/electron/electron/issues/11304. 
The root cause of the observed crashes was a concurrency bug. Another possible cause for this kind of behavior could be a NULL pointer returned from a RWLock factory.

Fix DesktopCapture crash on Mac OS X

---

patches/075-cherrypick_f1b7017a.patch

This CL makes sure that streams that get stalled on send are being put
back in the queue if they cannot send when attempting to unstall them.
https://chromium-review.googlesource.com/649849
Fixes electron/electron#11616.

Fix hanged large parallel POSTS in H2

---

patches/043-cherrypick_f1b7017a.patch

This CL makes sure that streams that get stalled on send are being put
back in the queue if they cannot send when attempting to unstall them.
https://chromium-review.googlesource.com/649849
Fixes electron/electron#11616.
Fixed in libcc/master in #435.

[1.8.x] Fix hanged large parallel POSTS in H2

---

patches/third_party/webrtc/003-connect_using_hostname_on_dns_failure_over_tls.patch

Addresses the problem described here:
https://bugs.chromium.org/p/webrtc/issues/detail?id=8102
where, after DNS resolution fails with a restrictive firewall, TLS
connections fail immediately.
As pointed out here in the bug:
https://bugs.chromium.org/p/webrtc/issues/detail?id=8102#c7
the problem is fixed with this change:
https://chromium-review.googlesource.com/c/external/webrtc/+/611520/9/webrtc/p2p/base/turnport.cc
which allows the connection attempt to proceed using the hostname as intended.

Backport WebRTC fix for connection failures with restrictive firewalls (1-8-x).

---

patches/third_party/webrtc/002-crop_video_to_prevent_freezes.patch

Fixes the problem documented in this bug:
https://bugs.chromium.org/p/webrtc/issues/detail?id=6958
where the encoder receives frame sizes it's not expecting and errors
out. The fix landed in M61:
https://codereview.webrtc.org/2936393002
This applies the critical pieces of that change to crop and scale poorly
sized frames before they hit the encoder.
Verified the fix with Slack video calling. It's easy to reproduce by
requesting a 641x480 getUserMedia stream from the camera. The logs will
be filled with this error:
```
Incoming frame doesn't match set resolution. Dropping.
```

Backport a WebRTC patch for video cropping to prevent freezes.

---

patches/third_party/webrtc/003-connect_using_hostname_on_dns_failure_over_tls.patch

Addresses the problem described here:
https://bugs.chromium.org/p/webrtc/issues/detail?id=8102
where, after DNS resolution fails with a restrictive firewall, TLS
connections fail immediately.
As pointed out here in the bug:
https://bugs.chromium.org/p/webrtc/issues/detail?id=8102#c7
the problem is fixed with this change:
https://chromium-review.googlesource.com/c/external/webrtc/+/611520/9/webrtc/p2p/base/turnport.cc
which allows the connection attempt to proceed using the hostname as intended.

Backport WebRTC fix for connection failures with restrictive firewalls (master).

---

patches/third_party/webrtc/004-ref-counted-dxgi-controller.patch

Dependent PR: electron/electron#11677
This patch (WebRTC PR: https://codereview.chromium.org/2933893003/) allows the `DXGIDuplicatorController` to unload when not in use. This is critical to get the fix for electron/electron#9933 into `1-8-x`. 
More detail:
As of now, the Electron thumbnail capturer runs in a different process than the WebRTC screen capturer. When we switch to the DirectX capturer for thumbnails to fix electron/electron#9933, it ends up forcing the `DXGIDuplicatorController` to be initialized twice (static variables are thread-safe, but not inter-process). Unfortunately, DXGI won't allow more than one duplicator per application, so the second one to be initialized ends up failing. The workaround this patch allows is to destroy the Electron thumbnail capturer and let the …

Backport WebRTC DirectX desktop capturer fix

---

.circleci/config.yml
Jenkinsfile
appveyor.yml
patches-mips64el/011-No-nss.patch
script/build
script/cibuild
script/create-dist

Linking with nss was causing crashes on mips64el platforms, the crash was coming from the system libsqlite3 which seemed to conflict with the forked libsqlite3 version inside Chromium:
```
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x000000ffe84e5bfc in sqlite3Malloc () at /lib64/libsqlite3.so.0
#2  0x000000ffe85d2cac in openDatabase () at /lib64/libsqlite3.so.0
#3  0x000000ffea8a8c84 in sdb_init () at /lib64/libsoftokn3.so
```
Turning off `use_nss_certs` can temporarily solve this problem, with the downside of making Electron's certificate related APIs not work.
We can probably solve this cleanly once Chromium [supports building with system sqlite](https://bugs.chromium.org/p/chromium/issues/detail?id=22208), but before that we are going to use this workaround while still exploring other …

Turn off use_nss_certs for mips64el

---

patches/044-can_disable_desktop_capture_throttling.patch
patches/075-can_disable_desktop_capture_throttling.patch

Backports #434 to the `electron-1-8-x`.

[1.8.x] [content] cherry-pick patch to allow disabling desktop capture throttling

---

Jenkinsfile
script/cibuild-libchromiumcontent-linux
script/create-dist
script/download
script/upload

The distribution packages are getting ever bigger. Especially after we switch to "official" builds, the static package can approach 3 GB due to bigger object files containing intermediate language code. Downloading such big files is tedious on slower connections and also Amazon intermittently closes long connections, making developer's life unbearable.
`tar.bz2` seems to be the best compression method readily available in Python 2.

Switch to `tar.bz2` for distribution package

---

script/download

The `t` is a file object, not a filename, so it must be passed to `tarfile.open` as a named argument.

Fix unpacking of downloaded artefacts

---

patches/077-fix-touchpad-lagging-issue.patch

This patch is for fix the Window Precision Touchpad lagging issue.  Port from https://chromium-review.googlesource.com/c/chromium/src/+/867070. Chromium will fix at M66. 
https://github.com/electron/electron/issues/8960

Add patch to fix touchpad lagging issue

---

chromiumcontent/BUILD.gn
chromiumcontent/config/BUILD.gn
patches/001-build_gn.patch
patches/v8/001-build_gn.patch
script/lib/gn.py
script/update

- For the `static_library` build, the Windows CI jobs take twice the time than necessary because Ninja always rebuilds everything during the second build pass (when it assembles the static libraries). This is due to the fact that the `update` script doesn't run GN via depot_tools, but directly. The second pass runs GN again, but this time from depot_tools and it causes the build command lines to be different from the first pass, which makes Ninja rebuild everything.
- I also cleaned up some syntax

Fix build issues

---

patches/fix-touchpad-lagging-issue.patch

https://github.com/electron/libchromiumcontent/pull/453
port the touchpad lagging fix to 1.7 for vscode.

Add patch to fix touchpad lagging issue to 1.7

---

patches/077_fix_mime_type_error.patch

Fixes https://github.com/electron/electron/issues/12011.
Patch [chromium commit](https://chromium.googlesource.com/chromium/src.git/+/6449de840aec46116c234a5865c4ba120a0e38d9) to fix es6 loading bug that caused
> Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
to be thrown when es6 modules attempted to be loaded. 
/cc @MarshallOfSound

fix mime type error for es6 modules

---

patches/v8/041-backport_a2b91ed.patch
patches/v8/042-backport_3ecb047.patch

Fixes these publicized security vulnerabilities:
https://bugs.chromium.org/p/project-zero/issues/detail?id=1445
Affects all Chromium versions up to 64
Backport for Cr63: https://github.com/electron/libchromiumcontent/commit/b12be538358e133331a52e3b995273cfedcf929b
Backport for Cr62: this PR
Backport for Cr61 (Electron 2.0): https://github.com/electron/libchromiumcontent/pull/463
Backport for Cr59 (Electron 1.8): https://github.com/electron/libchromiumcontent/pull/462
https://bugs.chromium.org/p/project-zero/issues/detail?id=1446
Affects Chromium 62 and 63 only
Backport for Cr63: https://github.com/electron/libchromiumcontent/commit/03a070f7794a8c0054ee841d57a2fdd30564391d
Backport for Cr62: this PR

Backport V8 security fixes

---

patches/v8/009-backport_3ecb047.patch

Bug report: https://bugs.chromium.org/p/project-zero/issues/detail?id=1445
Original change: https://chromium.googlesource.com/v8/v8/+/3ecb047abae69064052f268896afd3fe0824e0ce

Backported fix for V8 security issue (1.8)

---

patches/v8/026-backport_3ecb047.patch

Bug report: https://bugs.chromium.org/p/project-zero/issues/detail?id=1445
Original change: https://chromium.googlesource.com/v8/v8/+/3ecb047abae69064052f268896afd3fe0824e0ce

Backported fix for V8 security issue (2.0)

---

patches/002-dcheck.patch

Saw crash when running tests on Linux:
```
[4499:0307/103701.363973:FATAL:program_binding.h(419)] Check failed: IsContextLost(context_provider->ContextGL()).
0 0x7f4eb77c318d base::debug::StackTrace::StackTrace()
1 0x7f4eb77c155c base::debug::StackTrace::StackTrace()
2 0x7f4eb7851caa logging::LogMessage::~LogMessage()
3 0x7f4ec03b850a <unknown>
4 0x7f4ec03b38e7 <unknown>
5 0x7f4ec039ff4d viz::GLRenderer::SetUseProgram()
6 0x7f4ec03959f3 viz::GLRenderer::SetUseProgram()
7 0x7f4ec0391a64 viz::GLRenderer::DrawSolidColorQuad()
8 0x7f4ec03905db viz::GLRenderer::DoDrawQuad()
9 0x7f4eb6f15bc8 cc::DirectRenderer::DrawRenderPass()
10 0x7f4eb6f14316 cc::DirectRenderer::DrawRenderPassAndExecuteCopyRequests()
11 0x7f4eb6f13d24 cc::DirectRenderer::DrawFrame()
12 0x7f4ec0371f8d …
```

Disable DCHECK in program_binding.h

---

chromiumcontent/args/ffmpeg.gn
chromiumcontent/args/shared_library.gn
chromiumcontent/args/static_library.gn
patches/082-fix-arm64-linking-error.patch

Might be responsible for https://github.com/electron/electron/issues/12057, even if it does not fix the crash, it is still a good thing to align the config of arm64 with other architectures.

Do not use system freetype for arm64

---

chromiumcontent/args/ffmpeg.gn
chromiumcontent/args/shared_library.gn
chromiumcontent/args/static_library.gn
patches/082-fix-arm64-linking-error.patch

Backports #473 to 2-0-x, refs https://github.com/electron/electron/issues/12057.

 Do not use system freetype for arm64 (2-0-x)

---

patches/v8/009-backport_3ecb047.patch

Bug report: https://bugs.chromium.org/p/project-zero/issues/detail?id=1445
Original change: https://chromium.googlesource.com/v8/v8/+/3ecb047abae69064052f268896afd3fe0824e0ce
(cherry picked from commit c43a0e4f10d0211310405ea5a44f27471d5f81ce)
/cc @alespergl, @ckerr, @bpasero

Backported fix for V8 security issue (1.7)

---

chromiumcontent/args/static_library.gn
script/update

Due to problems in mips64el toolchain, the `--as-needed` linker flag crashes the compiler when we have official build enabled. Binary generated without the flag would potentially have symbols conflict between certain system libraries and Chromium's forked versions.
This PR is required for making Release build of mips64el work.
/cc @jkleinsc

Disable official build for mips64el (1.8.x)

---

chromiumcontent/BUILD.gn
chromiumcontent/args/tests.gn
script/build
script/run_tests
script/update

This PR tries to accomplish the first three action items in https://github.com/electron/libchromiumcontent/issues/360
```
$ ./script/run_tests
40 tests run.
The following 7 tests failed:
gpu_unittests
blink_platform_unittests
base_unittests
content_unittests
net_unittests
compositor_unittests
content_browsertests
```

Enable unittests and browsertests

---

patches/002-dcheck.patch

This DCHECK was triggering in the following situation:
1. Open a new window by clicking a `target=_blank` link to a web origin, e.g. `http://localhost:8080`
2. In that window, click a link that will cause navigation, e.g. `<a href='/'>`
Since Electron maintains its own history book-keeping, there's no need for this DCHECK.

Comment out a DCHECK that was hitting when navigating in a guest window

---

script/build-clang.py
script/lib/config.py
script/package-clang.py
script/update

In order to build/test Electron on arm64 we need to manually build clang for arm64.  These scripts are modified versions of https://chromium.googlesource.com/chromium/src/tools/clang/+/master/scripts/update.py and https://chromium.googlesource.com/chromium/src/tools/clang/+/master/scripts/package.py
`package-clang.py` includes logic to upload to s3 so that we can pull arm64 binaries from s3 for Electron arm64 builds.  In theory these scripts should also be able to be used to create armv7 binaries so that we can test on armv7 hardware.
My intention with these scripts is that they would be run on demand from our arm64-ci, eg: https://arm64-ci.electronjs.org/blue/organizations/jenkins/clang-build/detail/clang-build/18/pipeline because they only need to be run when our clang revision changes. …

Customized build clang scripts for arm64

---

patches/common/chromium/disable_base_computed_style_dcheck.patch

This `DCHECK` is for some reason causing failures in `electron-api-demos` for reasons that i've investigated but can't fully determine; i'm disabling this check for now as a mitigation and will look to more fully investigate and re-add the check in later.
/cc @ckerr

add patch to disable base_computed_style_ DCHECK

---

patches/043-fix_rendering_glitches_on_high_sierra.patch
patches/083-vs_toolchain.patch

As per https://bugs.chromium.org/p/chromium/issues/detail?id=773705#c141, I am aligning the patch with upstream. Might improve the state of https://github.com/electron/electron/issues/12042
```
Re-enabling accelerated 2D Canvas, as without acceleration performance
was bad enough that Canvas2D became unusable in common cases. If
deciding between occasional visual corruption and unusable performance,
visual corruption seems to be the lesser issue.
Note that this keeps GPU Raster blacklisted. This is unfortunate, but
was only enabled 1yr ago, so should have less sites with a hard
dependency.
```
CL: https://chromium-review.googlesource.com/c/chromium/src/+/759236
/cc @bpasero @Tyriar

[2-0-x]: Re-enable accelerated 2D Canvas on NVidia High Sierra

---

script/bootstrap

I was seeing the following error on macOS when running the bootstrap script.
`error: can't combine user with prefix, exec_prefix/home, or install_(plat)base`
This fixes it.

Fix bootstrap install error

---

patches/common/chromium/.patches.yaml

Now we have 65 .patch files in the "common/chromium/" and 65 entries in the .patches.yaml.

Add missing patch to the config

---

patches/042-high-sierra-nvidia-gpu.patch

Backports https://github.com/electron/libchromiumcontent/pull/489

[1-8-x]: Re-enable accelerated 2D Canvas on NVidia High Sierra

---

patches/common/chromium/.patches.yaml
patches/common/chromium/compositor_delegate.patch

Update patch based on [this](https://bitbucket.org/chromiumembedded/cef/src/173d79a417b97aa62216d3c54531a4671aa3ff1f/patch/patches/compositor_1368.patch?at=3359&fileviewer=file-view-default) update for Chromium 66.
Compensates for changes made in [this patchset](https://chromium-review.googlesource.com/c/chromium/src/+/722207).
For https://github.com/electron/libchromiumcontent/pull/499.
/cc @brenca @alexeykuzmin @deepak1556

Fix compositor delegate patch

---

patches/common/chromium/.patches.yaml
patches/common/chromium/disable-redraw-lock.patch

Fixes electron/electron#1821, sister PR coming up on that repo
When DWM is disabled, chromium uses a custom window title implementation (this can be observed by running Chrome on Windows7 with the aero theme disabled). The code is written to assume that that's what's happening, but electron is forcing a native titlebar, and that causes problems, since chromium does [some hacky stuff](https://cs.chromium.org/chromium/src/ui/views/win/hwnd_message_handler.cc?l=253) to ensure that the custom titlebar always works perfectly. That hacky stuff blocks the native titlebar (and the whole window in fact) from rendering correctly. This patch adds a way to disable the lock.

Add a patch to fix window repainting issues when DWM is disabled on Windows

---

patches/046-backport_72d995cf.patch
patches/047-backport_d007b8b7.patch

Backports [72d995cf2cc67c9c8aa7164f6d72d7aa3380a35c ](https://chromium.googlesource.com/chromium/src/+/72d995cf2cc67c9c8aa7164f6d72d7aa3380a35c) and [d007b8b750851fe1b375c463009ea3b24e5c021d](https://chromium.googlesource.com/chromium/src/+/d007b8b750851fe1b375c463009ea3b24e5c021d). Related to https://github.com/electron/electron/issues/12552.
There's no PRs to master or other branches since Chromium 60+ is not affected.
/cc @ckerr, @deepak1556

Backport a couple of IndexedDB fixes

---

script/get-patch
script/lib/git.py

Use it to export commits from Chromium's and other repos as patch files. E.g.
```
$ ./script/get-patch --repo src --commit 72d995cf2 > some/folder/path/backport_72d995cf2.patch
```
/cc @MarshallOfSound, @deepak1556, @alespergl

Add script/get-patch

---

patches/third_party/webrtc/005-mac_invalid_cursor_screenshare_crash.patch

Backports the change here:
https://chromium.googlesource.com/external/webrtc/trunk/webrtc/+/07961e9d2becadcf9419cede22aa0bf3058ccaa2%5E%21/#F0
fixing the crash reported here:
https://bugs.chromium.org/p/chromium/issues/detail?id=752036
(requires a chromium.org account to view)
We've had crashes with the same stack trace reported by Slack screen
sharing users. Since we can't reproduced the crash internally, I haven't
been able to verify the fix, but by inspection it's very likely to work.
The upstream fix was released in M60 so this isn't as issue in Electron
2.x which uses M61. We've verified this with users.

Add a patch to fix a Mac screen sharing crash.

---

patches/084-backport_0a29c32.patch
patches/085-backport_f398005.patch

**[Windows Sandbox] Possible short/8.3 form native file paths prevent startup.**
https://chromium-review.googlesource.com/580629
Fixes https://crbug.com/744638, landed in 62.0.3181.0.
**Backport "Reimplemented GetProcessBaseAddress"**
https://chromium-review.googlesource.com/608702
Fixes https://crbug.com/753140, landed in 62.0.3187.0.
No need to merge both into `master`, it has Chromium 63.
/cc @ckerr

Backport a couple of sandbox fixes from Chromium

---

vsts.yml

#515 added the VSTS build logs as comments in the PR, but unfortunately did not capture error output (aka stderr).  This PR adds the capture of that information.

Add error output to VSTS build logs

---

vsts.yml

Mac static builds were accidentally building the shared library instead of the static library on VSTS.

Fix Mac static builds on VSTS

---

vsts.yml

Static builds were accidentally building the shared library instead.
Backports #523 to 2-0-x
(cherry picked from commit b9a74d0dbea4454fa9301d9871a026f0d2dcd8a9)

Fix mac static builds for 2-0-x

---

vsts.yml

Visual Studio Team Services builds PRs by merging the commit(s) into the target branch and then building that.  Unfortunately this ends up putting PR builds in the wrong location on S3 as well as it produces issues for WIP PRs such as our Chromium upgrades.
This PR will do the following:
1. If the build is not a PR build, it will build the commit.
2. If the build is a PR build, but for a fork, it will build against the result of merging the commit(s) into the target branch.
3. If the build is a PR build from a branch in this repo, it will build the original commit instead of the merge.

Fix PR builds for Mac

---

patches/048-render_widget_compositor.patch

(cherry picked from commit bf95c72597ae78987bc098c2211fa1dcb33c32bd)
Port #331 to `1-8-x`. Master (Chromium 63) and 2.0.x (Ch61) are not affected.
Fixes electron/electron#9413.

Backport fix for flickering web contents on large monitors

---

vsts.yml

This PR should fix VSTS so that we only run PR builds for PRs coming from forks.  All PRs that come from branches will get built automatically as branch builds.

Only run builds if they are branch build or fork pr for VSTS

---

.circleci/config.yml
appveyor.yml
chromiumcontent/BUILD.gn
script/cibuild
script/cibuild.ps1
script/run_tests
vsts.yml

This is a continuation/replacement of #529.
This PR adds the necessary CI config changes to run the chromium tests and report them in the various CI platforms.

Update run_tests to generate xml reports for CI

---

patches/common/webrtc/.patches.yaml
patches/common/webrtc/fix_jitter_buffer_with_opus_dtx.patch

This backports the fix for:
https://bugs.chromium.org/p/webrtc/issues/detail?id=8488
which landed upstream in M64.
It's a critical fix for any WebRTC service that makes use of discontinuous transmission (DTX), like Slack calls. When it is triggered, the bug manifests as increased delays and severe audio dropouts.
The patch is a combination of these two CLs:
https://webrtc-review.googlesource.com/c/src/+/18181
https://webrtc-review.googlesource.com/c/src/+/44420
(the latter just to make the fix permanent)
**Testing**
I can repro the issue in Slack. I verified a build with this patch against the `electron-2-0-x` branch resolves it.

Add patch to fix long jitter buffer delays with Opus and DTX.

---

patches/third_party/webrtc/004-fix_jitter_buffer_with_opus_dtx.diff

This brings the patch in #532 to `electron-2-0-x`.

Add a patch to fix long jitter buffer delays with Opus and DTX (2.0.x edition) 

---

chromiumcontent/args/ffmpeg.gn
chromiumcontent/args/shared_library.gn
chromiumcontent/args/static_library.gn
chromiumcontent/args/tests.gn
patches/common/chromium/build_gn.patch
patches/common/v8/build_gn.patch
script/build
script/update

This is to support compatibility with the GN build, which checks out the
libchromiumcontent repo at `src/libchromiumcontent`.

Move //chromiumcontent to //libchromiumcontent/chromiumcontent

---

DEPS
patches/common/chromium/build_gn.patch

Supports building Electron alongside Chromium.
Depends on #536. See also [electron/electron#12837](https://github.com/electron/electron/pull/12837).

GN build support

---

script/build
script/create-dist
script/run-gn
script/update

This PR changes script/build to not build native_mksnapshot if you are not on hardware capable of building those binaries.  Fixes #509

Only build native_mksnapshot for arm and arm64

---

.circleci/config.yml
chromiumcontent/args/native_mksnapshot.gn
patches/common/chromium/.patches.yaml
patches/common/chromium/backport_4dabe8070550.patch
script/cibuild
script/download
script/lib/config.py
script/lib/filesystem.py
script/update
script/upload
vsts.yml

This PR adds the capability of using a tarball cache of the chromium source code to speed up builds. 
The tarballs are stored on S3 by platform and chromium version (eg `libchromiumcontent/linux/src/63.0.3239.150/src.tar.bz2`).  If the tarball doesn't exist for the version/platform, then the source will be downloaded using `gclient sync`.  In this case if the `upload_packaged_src` argument is passed to `script/update`, then the source will be archived and uploaded to S3. 
To use this feature, pass the `use_packaged_src` argument when calling `script/update`.
The chromium source that is archived does not have the `.git` directories or the `native_client` directory.
The tarball sizes for 63.0.3239.150 are as follows:
- Linux - 1.9 gb
- Windows 1.5gb
- OSX - 1.4gb
It may be possible to …

Use packaged chromium source to speed up CI builds

---

patches/common/chromium/.patches.yaml
patches/common/chromium/crashpad-disabled-windows.patch

Electron, release build, will not link on Windows if Chromium depends on symbols from Crashpad. I have added a patch which should disable Crashpad in Chromium and activate fallback to Breakpad.

fix: Patch to disable Crashpad in Chromium on Windows

---

patches/common/v8/.patches.yaml
patches/common/v8/backport_2eb23a17.patch
patches/common/v8/backport_50206308.patch

This backports two commits to fix the array splice regression caused in ch66.
The patches represent those commits and fixing some merge conflicts etc.
Please suggest a sensible number for the patch version for v8.
This addresses https://github.com/electron/electron/issues/13153.

Patches to backport the array splice performance regression caused in ch66.

---

patches/086-backport-f0c82253.patch

https://chromium-review.googlesource.com/677290

backport: Allow lookup of videodecoder service to fix HW video decoding on macOS 10.13

---

patches/common/webrtc/.patches.yaml
patches/common/webrtc/backport_a157e0809.patch

https://webrtc-review.googlesource.com/73701
Landed in 67.0.3396.62
TODO: Backport the change to 2.0 and maybe to 1.8 branches.

backport: VP9 temporal index bounds check

---

patches/086-backport-f0c82253.patch

Fixes regression introduced in https://github.com/electron/libchromiumcontent/pull/557
The patch relies on changes introduced in https://chromium.googlesource.com/chromium/src/+/c5045f3a803a8375502ab153ce61bc6944c0ee28, which I've missed before.

Fix patches/086-backport-f0c82253.patch

---

patches/common/chromium/.patches.yaml
patches/common/chromium/boringssl_build_gn.patch

Adds in some functions from boringssl that aren't built by default in Chromium, but which node.js needs. Without these, nodejs fails to link against boringssl.

chore: [gn] make boringssl nodejs-compatible

---

vsts.yml

This PR backports our VSTS configuration from master to the 2-0-x branch.
This allows us to break up VSTS builds into separate builds which gives more discrete build statuses and also allows us to just restart one build instead of all 4 builds.

Use new VSTS config from master

---

patches/common/chromium/dcheck.patch

This reverts commit b9a68acb7e1f93193540cdf94f73ad6ba22c7900.
It seems this DCHECK is ok and should be reenabled now.
Electron doesn't crash with this DCHECK being enabled: https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.5964
Fixes electron/electron#13317.

Revert "Disable a DCHECK in process_metrics_win.cc"

---

patches/common/chromium/.patches.yaml
patches/common/chromium/wtl_warnings.patch

Chromium doesn't use this bit of WTL, so they haven't bothered to fix the warnings that are generated in these headers.

chore: fix WTL warnings when building w GN

---

patches/common/chromium/.patches.yaml
patches/common/chromium/no_cache_storage_check.patch

In Electron we may have scripts running without an origin (for example from Node.js), and it will trigger an assertion in `CacheStorage`. The chromium commit introduced the check is https://chromium.googlesource.com/chromium/src/+/b6a21896d9687ff8c7c6aa809e45b3efe2fefb50%5E%21/#F0.
This patch intends to disable a behavior instead of temporarily disabling a check, so I did not put it in `dcheck.patch`.
This should be able to fix the second crash in https://github.com/electron/electron/issues/12835#issuecomment-398941227.

Do not check for unique origin in CacheStorage

---

patches/common/chromium/.patches.yaml
patches/common/chromium/no_cache_storage_check.patch

Backports https://github.com/electron/libchromiumcontent/pull/577 to 3-0-x

Do not check for unique origin in CacheStorage (3-0-x)

---

patches/mas/chromium/no_private_api.patch

Backports https://github.com/electron/libchromiumcontent/pull/580 to `electron-3-0-x`.

Remove some new private APIs in MAS build (3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/blink_fix_prototype_assert.patch

Refs https://github.com/electron/electron/issues/13316.
A recent Chromium change has accidentally added assertion for the case when a new window object may not have a prototype attached. In Electron it may happen when preventDefault for a native new-window event.
https://chromium.googlesource.com/chromium/src/+/f47b361887a31cccf42a6e21a82bccf28372bdaa%5E%21
In the long term we should investigate why it happened, and take a more formal fix. But for now I'm just make this assertion silently pass away.

Fix assertion when preventDefault is called for new-window

---

vsts.yml

For PR builds on branches we don't build anything, but we need to do something so that VSTS updates the status on GitHub for the pr builds.  This PR adds a simple bash echo to make sure that VSTS marks the PR builds as complete.

Force VSTS to update status for PR builds

---

patches/common/chromium/build_gn.patch
patches/common/icu/build_gn.patch
patches/common/v8/build_gn.patch

When building Electron with GN in release mode, all code is linked
statically into a single binary, including node & v8. This is in
contrast to the GYP build, in which node, v8 and icu are linked as a
shared library (due to openssl symbol conflicts).
This change adds a `is_electron_gn_build` flag which defaults to false,
allowing those libraries to be built statically in the GN build, but
be built as a shared library when libcc is to be consumed by the GYP
build of Electron.

chore: [gn] build icu & v8 statically in GN build

---

patches/common/chromium/.patches.yaml
patches/common/chromium/disable_scroll_begin_dcheck.patch

When testing https://github.com/electron/electron/issues/13137 I have encountered these assertions. I grouped them together since they are all related to the ScrollBegin event.

Disable DCHECKs related to ScrollBegin event

---

appveyor-override.yml
script/build
script/create-dist

This PR updates the 2-0-x branch to use Visual Studio 2015 because Visual Studio 2017 is now the default.

Use Visual Studio for 2-0-x

---

patches/common/chromium/.patches.yaml
patches/common/chromium/gtk_visibility.patch

Without this, GN throws an error saying that targets in //electron and //electron/brightray aren't allowed to depend on //build/config/linux/gtk.

build: [gn] allow electron targets to depend on gtk

---

patches/common/chromium/.patches.yaml
patches/common/chromium/libgtkui_export.patch

Without these, the GN build would throw errors like
```
ld.lld: error: undefined symbol: libgtkui::Gtk2StatusIcon::Gtk2StatusIcon(gfx::ImageSkia const&
, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)
>>> referenced by tray_icon_gtk.cc:43 (../../electron/atom/browser/ui/tray_icon_gtk.cc:43)
>>>               tray_icon_gtk.o:(atom::TrayIconGtk::SetImage(gfx::Image const&)) in archive obj/electron/libelectron_lib.a
```

build: [gn] export libgtkui symbols

---

patches/common/chromium/.patches.yaml
patches/common/chromium/backport_e3a883075.patch
patches/common/chromium/dcheck.patch

Backporting the same fix which is already merged in master libcc in commit a5e6964a1d4a5a4bd8a580c5a365ad5d6ff6f6e5 to 3.0.x branch.

fix: Process metrics fix backport

---

script/download

As part of #590, I made changes to only show download percentage when running with verbose (-v) mode in this commit: bdfcdb0fe1f4d94755e04fcf65a5767d4055d1d5.  This broke the static libcc download.  This PR fixes that.

Fix static download

---

patches/common/chromium/.patches.yaml
patches/common/chromium/sysroot.patch

The GYP build uses a version of `install-sysroot.py` that was copied out of `//build/linux/sysroot_scripts` some time ago. This change will only affect GN, and it will cause the GN build to use the custom-built Electron sysroots, stored at http://s3.amazonaws.com/gh-contractor-zcbenz/toolchain and maintained by @zcbenz, instead of chromium's sysroots.
I'm not terribly satisfied with this solution, as it means we need to expend effort to maintain up-to-date sysroots. As far as I know, the only reason we build our own sysroot is to add the `libnotify` headers. Some other solutions that might allow us to use chromium's sysroot unmodified:
- we could build an 'overlay' sysroot, which we could extract on top of the sysroot that chromium builds, with just the libnotify headers (and whatever …

build: [gn] use electron's custom sysroots

---

script/create-dist

This cherry-picks for #609 for 3.0.x.

build: Ship libbase_static.a for macOS/Linux (3.0.x)

---

patches/common/chromium/build_gn.patch

Fixes link errors of the form:
```
node.lib(node_lib.Protocol.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in atom_main.obj
```
This is because in the GN build, node is linked statically instead of
dynamically in non-component builds.

build: [gn win] link against static crt in non-component builds

---

patches/common/chromium/resource_file_conflict.patch

We don't use this target, but gn refuses to generate the Release build files on Linux without this:
```
ERROR Input to targets not generated by a dependency.
The file:
//out/Release/locales/en-US.pak
is listed as an input or source for the targets:
//chrome/installer/linux:stable_deb
//chrome/installer/linux:stable_rpm
//chrome/installer/linux:beta_deb
//chrome/installer/linux:beta_rpm
//chrome/installer/linux:unstable_deb
//chrome/installer/linux:unstable_rpm
but this file was not generated by any dependencies of the targets. The target
that generates the file is:
//electron:packed_resources_locales_en-US
```

build: [gn] redirect //chrome:packed_resources to //electron's version

---

patches/common/chromium/.patches.yaml
patches/common/chromium/scroll_bounce_flag.patch

Backports https://github.com/electron/libchromiumcontent/pull/613 to `electron-3-0-x`.

Add patch to make scrollBounce option work (3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/scroll_bounce_flag.patch

This patch makes the renderer process to use `--scroll-bounce` command line flag to enable rubber banding.
This is required to fix https://github.com/electron/electron/issues/13493.
Chromium does not provide a way for us to inject code just before renderer process is started, when Chromium reads system rubber banding setting. I tried to set `NSScrollViewRubberbanding` in a few places but they all have race conditions when creating multiple windows with different settings, see https://github.com/electron/electron/pull/13797 for an example.
This patch is the simplest solution (and probably the most decent one) that I can find, and it is very easy to maintain.

Add patch to make scrollBounce option work

---

patches/common/chromium/.patches.yaml
patches/common/chromium/backport_d65792a.patch

See https://chromium-review.googlesource.com/c/chromium/src/+/1105698
This fixes electron/electron#13256.

fix: Backport patch to fix Widget::OnSizeConstraintsChanged crash

---

patches/common/chromium/.patches.yaml
patches/common/chromium/backport_d65792a.patch

fix: Backport patch to fix Widget::OnSizeConstraintsChanged crash (3.0.x)

---

patches/089-backport_d65792a.patch

fix: Backport patch to fix Widget::OnSizeConstraintsChanged crash (2.0.x)

---

patches/090-backport_6af3ad0.patch

This is a backport of
https://chromium-review.googlesource.com/c/chromium/src/+/687832
targeting the 2-0-x branch of Electron.
This is a crucial patch for Figma, since without it Mac users will see
flickering when their GPU is under heavy load.

fix: Backport "Enforce flush ordering between contexts in GPU process on macOS" (2-0-x)

---

patches/091-backport_1f6e069.patch

This is a backport of
https://chromium-review.googlesource.com/c/chromium/src/+/696666
targeting the 2-0-x branch of Electron.
This is a follow up to #624, which backported a commit which preceeded this one. It turns out that we need both in order to actually resolve the problem.

fix: Backport "Use unverified sync token in WebGL's DrawingBuffer."

---

patches/common/boringssl/.patches.yaml
patches/common/boringssl/0001-Implement-legacy-OCSP-APIs-for-libssl.patch

One of Electron's tests exposed the fact that boringssl didn't support the OCSP stapling APIs that nodejs was calling. This backports a patch from boringssl that adds the APIs that nodejs expects, and causes the test to pass.

fix: backport legacy OCSP APIs in boringssl

---

patches/common/chromium/.patches.yaml
patches/common/chromium/webview_reattach.patch

Applies https://chromium-review.googlesource.com/c/chromium/src/+/1161391.
Fixes webview not working after renderer process restarted.
Refs https://github.com/electron/electron/pull/13869 and https://github.com/electron/electron/issues/12291.

fix: reattach webview after renderer process restarts

---

patches/common/chromium/.patches.yaml
patches/common/chromium/webview_reattach.patch

Backports https://github.com/electron/libchromiumcontent/pull/629 to `electron-3-0-x`.

fix: reattach webview after renderer process restarts (3-0-x)

---

patches/common/v8/.patches.yaml
patches/common/v8/backport_91ddb65d.patch
patches/common/v8/backport_aa6ce3e.patch
patches/common/v8/cherry-pick_5dd3395.patch
patches/common/v8/cherry-pick_6989b3f6d7.patch
patches/common/v8/cherry-pick_70c4340.patch
patches/common/v8/cherry-pick_a440efb27f.patch
patches/common/v8/cherry-pick_acc336c.patch
patches/common/v8/cherry-pick_b20faff.patch
script/README.md

This PR adds patches for the Node upgrade to `v10.6.0`. It also corrects the `get-patch` script doc for the `--output-dir` cli flag.

src: add patches for Node upgrade v10.6.0

---

patches-mas/004-no-cgdisplayusesforcetogray-cfisobjc.patch

see #633 
Ref electron/electron#13938
The patches for `AudioDeviceDuck` and `_LSSetApplicationLaunchServicesServerConnectionStatus` aren't needed as those APIs were not present in Chromium 61.

fix: backport MAS api removal to 2-0-x

---

patches/common/chromium/.patches.yaml
patches/common/chromium/allow_webview_file_url.patch

By default Chromium does not allow webview to load non-web URLs like `file://`, this patch disables the behavior.
This is required by https://github.com/electron/electron/pull/13869.

fix: allow webview to load non-web URLs

---

patches/common/chromium/.patches.yaml
patches/common/chromium/allow_webview_file_url.patch

Backports https://github.com/electron/libchromiumcontent/pull/635 to `electron-3-0-x`.

fix: allow webview to load non-web URLs (3-0-x)

---

patches/common/crashpad/.patches.yaml
patches/common/crashpad/http_status.patch

Since the GN build uses the crashpad that's referenced by Chromium's
DEPS, port over the one semantic change from Electron's crashpad fork to
be a patch.

fix: [gn] port crashpad patch from fork to patch

---

appveyor-override.yml

@MarshallOfSound and @deepak1556 discovered that electron/electron#13618 was caused by the version of Visual Studio that we built with.  This PR changes the 3-0-x branch to use Visual Studio 2017 v15.4.5 which resolves the issue.

Use Visual Studio 2017 v15.4.5 for 3-0-x

---

vsts.yml

We recently built 1-7-x for #639 and it was the first time doing so with VSTS.  It turns out the way that 1-7-x builds the zip files was causing issues with the S3 upload.  This PR updates VSTS to only upload the zip file for the type of build being done (static or shared).

Change to only copy proper file to s3

---

appveyor-override.yml

Use Visual Studio 2017 15.4.5 instead of vs2017-15.7.4
@MarshallOfSound and @deepak1556 discovered that electron/electron#13618 was caused by the version of Visual Studio that we built with. This PR changes the master branch to use Visual Studio 2017 v15.4.5 which resolves the issue.
(cherry picked from commit ff3f2a71da778cd8c366b08681ba6b3f59b02606)

Use VS2017 15.4.5 for Chromium 66

---

patches/common/angle/.patches.yaml
patches/common/boringssl/.patches.yaml
patches/common/chromium/.patches.yaml
patches/common/crashpad/.patches.yaml
patches/common/crashpad/http_status.patch
patches/common/ffmpeg/.patches.yaml
patches/common/icu/.patches.yaml
patches/common/skia/.patches.yaml
patches/common/v8/.patches.yaml
patches/common/webrtc/.patches.yaml
patches/mips64el/chromium/.patches.yaml
patches/mips64el/ffmpeg/.patches.yaml
patches/mips64el/v8/.patches.yaml
script/apply-patches
script/lib/git.py
script/lib/patches.py
script/patch.py

Adds an optional `--commit` arg to the `apply-patches` script.
Shouldn't affect regular builds in any way, but will allow the GN build to commit libcc patches after they have been applied to prevent issues with untracked files in the Chromium tree.
Step 2 of this change will be converting all `.patch` files to a format that [`git-format-patch`](https://git-scm.com/docs/git-format-patch) understands, this way we will get rid of authors and descriptions in the `.patches.yaml` files and will be able to commit those patches easier.
It will be done in a separate PR.
/cc @nornagon

build: optionally commit patches after they have been applied

---

patches/093-roll-clang.patch

See upstream:
https://chromium-review.googlesource.com/c/chromium/src/+/582074
We don't need any of the other changes from that CL, because they're all
fuchsia- or iOS-only.
Ref electron/electron#13988

chore: roll clang 307486:308728

---

script/apply-patches
script/lib/patches.py
script/patch.py

It is necessary because we have different folders hierarchy
in traditional build setup with libchromiumcontent being a separate repo
and in gn-based build with libchromiumcontent repo checked out inside the src/.
Usage:
`./script/apply-patches --project-root=SRC_PARENT_FOLDER`

build: Add optional --project-root arg for the patching related scripts

---

patches/common/chromium/.patches.yaml
patches/common/chromium/enable_osr_components.patch

Backport [this commit](https://bitbucket.org/chromiumembedded/cef/commits/fad6aec5d0f02853ff6b8af403c5b75d4764e3cb) from CEF in order to add `MouseWheelPhaseHandler` in osr. 
Related: https://github.com/electron/electron/pull/14074
/cc @brenca @alexeykuzmin @deepak1556

fix: add patch to re-enable osr MouseWheelPhaseHandler

---

patches/common/chromium/.patches.yaml
patches/common/chromium/enable_osr_components.patch

Backport of https://github.com/electron/libchromiumcontent/pull/649.
/cc @brenca @deepak1556 @alexeykuzmin

fix: add patch to re-enable osr MouseWheelPhaseHandler (backport 3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/ignore_rc_check.patch

Build compiles rc files twice once with rc.exe and another with rc.py. Ignoring comparison of output in the build due to a bug in rc.py

build: ignore comparison differences between res files

---

script/lib/git.py
script/lib/patches.py

This updates @alexeykuzmin's commit logic to commit our patches in batches so that we don't run commit a lot of times on a massive repo.  This drops the re-sync time from 10 minutes to 2 minutes on my local machine, disabling commits drops it to 1min 52 seconds so this is wayyy better now 👍

perf: commit our patches in batches instead of 1 by 1

---

patches/common/chromium/.patches.yaml
patches/common/chromium/content_browser_manifest.patch

Required for https://github.com/electron/electron/pull/14253

fix: allow content_browser service to access GeolocationControl interface

---

patches/common/chromium/.patches.yaml
patches/common/chromium/dcheck.patch

It gets constantly triggered on Windows CI, e.g.
https://windows-ci.electronjs.org/project/AppVeyor/electron-i8wjp/build/1.0.91
We expect that backporting of https://chromium-review.googlesource.com/802574
should fix it.

build: disable a DCHECK in viz::ServerSharedBitmapManager

---

patches/common/chromium/.patches.yaml
patches/common/chromium/vmware_gpu_acceleration.patch

Backports https://github.com/electron/libchromiumcontent/pull/665

fix: Re-enable GPU acceleration for recent VMWare drivers (backport: 3-0-x)

---

chromiumcontent/args/shared_library.gn
chromiumcontent/args/static_library.gn

The flag got guarded behind `is_chrome_banded` in https://webrtc-review.googlesource.com/c/src/+/36321 , although it got reverted in https://webrtc-review.googlesource.com/c/src/+/62380 we cannot be sure that might not happen in future for the reasoning in that CL. So we explicitly override it, whenever we build with `proprietary_codecs`
Fixes https://github.com/electron/electron/issues/14256

build: [gyp] explicitly override rtc_use_h264

---

chromiumcontent/args/shared_library.gn
chromiumcontent/args/static_library.gn

Backports https://github.com/electron/libchromiumcontent/pull/667

build: [gyp] explicitly override rtc_use_h264 (backport: 3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/add_realloc.patch
patches/common/v8/.patches.yaml
patches/common/v8/add_realloc.patch

This PR was previously opened and then closed, because we believed we could implement the needed changes on the `electron/node` side without needing to change libcc. However, as a result of [this change](https://github.com/electron/node/commit/efa2380edfbc95be0b5bf189303c58fc75c99c1c#diff-24260586604e0dc8a2dc3ad5812a93bbR197) we do in fact need to implement it. This is because the alternative, implementing with `memcpy`, requires knowledge of how many bytes are needed for the memcpy and we can't know that. 
/cc @ckerr

feat: implement ArrayBuffer realloc

---

patches/common/chromium/.patches.yaml
patches/common/chromium/blink_initialization_order.patch

Fixes https://github.com/electron/electron/issues/13787
Backport of https://chromium-review.googlesource.com/c/chromium/src/+/1030530 to fix the order of V8 and Blink initialization.  Also fixes the order of `DidCreateScriptContext` notification with initialization of window globals to fix electron/electron#13787.  The backport landed in Chromium 67 but the `DidCreateScriptContext` re-ordering needs to be upstreamed or kept indefinitely
cc @deepak1556

fix: add patch for blink initialization order

---

patches/common/chromium/.patches.yaml
patches/common/chromium/blink_initialization_order.patch

Backport https://github.com/electron/libchromiumcontent/pull/672 to `3-0-x`
/cc @MarshallOfSound

fix: add patch for blink initialization order (3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/allow_nested_error_trackers.patch

Backport https://github.com/electron/libchromiumcontent/pull/673 to `3-0-x`
/cc @ckerr

fix: workaround for X11ErrorTrackers issue (3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/disable_detach_webview_frame.patch

This is part of fixes for https://github.com/electron/electron/issues/14211.
As explained in https://github.com/electron/electron/issues/14211#issuecomment-418616406, Chromium has some race conditions when managing WebFrame of webview that, it will sometimes accidentally detach the WebFrame of webview, resulting in the WebContents of webview being wrongly destroyed.
This patch disables Chromium's ability to detach the WebFrame of webview. There will be another patch in Electron to manually manage the WebContents of webview on Electron's side.

fix: do not let Chromium manage webview's frame's lifetime

---

patches/common/chromium/.patches.yaml
patches/common/chromium/disable_detach_webview_frame.patch

Backports https://github.com/electron/libchromiumcontent/pull/676 to `electron-3-0-x`.

fix: do not let Chromium manage webview's frame's lifetime (3-0-x)

---

patches/common/chromium/.patches.yaml
patches/common/chromium/leveldb_ssize_t.patch

node.js (and its dependencies) define the `ssize_t` type in their headers on Windows, using a guard to prevent redefinition. leveldb also defines the `ssize_t` type in the `port_chromium.h` file, but without the redefinition guard. This causes a compilation error on windows, because the type is defined twice when compiling `atom_api_browser_window.cc` in electron.

fix: [m67] patch leveldb to not redefine ssize_t
